apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ko2e9e83g-java-quarkus
  janus-idp.io/tekton: ko2e9e83g-java-quarkus
  backstage.io/kubernetes-id: ko2e9e83g-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ko2e9e83g-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
